# NUMPY Introduction
* used for working with arrays
* we can use it for linear algebra, Fourier transform, signal processing, and matrix operations
* numpy : numerical python
* created in 2005 by Travis E. Oliphant
* why numpy?
    * it is fast , in python we have list that will be slower
    * Numpy aims to provide a high-performance array object, 50x faster than a Python list
* why Numpy array faster than list?
* in Numpy Array we are using same data type for all elements
* in list we can use different data types
* Numpy written in C or C++ for speed or fast computation
* pip install numpy
* ! / %

In [2]:
import numpy as np
print(np.__version__)

2.2.6


In [5]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
# Dimensions
# pandas.series : one dimensional labeled array 
# pandas.DataFrame : two dimensional labeled array

In [13]:
# 0-D array
import numpy as np
arr = np.array(42)
print(arr)
print("dimensions of arr: ",arr.ndim)

42
dimensions of arr:  0


In [16]:
# 1-D Array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print("shape of arr1: ",arr1.shape)
print("dimensions of arr1: ",arr1.ndim)

[1 2 3 4 5]
shape of arr1:  (5,)
dimensions of arr1:  1


In [ ]:
# 2-D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape)
print("dimensions is: ",arr2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
dimensions is:  2


In [20]:
# 3-D Array
arr3 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])
print(arr3)
print("shape is:",arr3.shape)
print("Dimensions are:",arr3.ndim)

[[[1 2 3 4]
  [4 5 6 7]]

 [[1 2 3 4]
  [4 5 6 7]]]
shape is: (2, 2, 4)
Dimensions are: 3


In [22]:
# create 5 dimensional array
arr5 = np.array([1,2,3,4],ndmin=5)
print(arr5)
print(arr5.shape)
print("number of dimensions",arr5.ndim)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)
number of dimensions 5


In [27]:
# access the array elements using indexing
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[5])

6


In [28]:
# get third and fifth element from this array and add them together
print(arr[3] + arr[5])

10


In [36]:
# in 2d Array we can access the elements by row and column
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2[0])
print(arr2[1])
print("3 element of second row: ",arr2[1,2])
print("2nd element of first row:",arr2[0,1])

[1 2 3 4 5]
[ 6  7  8  9 10]
3 element of second row:  8
2nd element of first row: 2


In [46]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3.ndim)
print(arr3[0])
print(arr3[0,0])
print(arr3[0,0,0])
print(arr3[1,0,1])
print(arr3[1,1,-1])
print(arr3[-1,-2,-1])


3
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
8
12
9


In [54]:
# slicing [start:end:step]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[2:8])
print(arr[4:])
print(arr[:4])
print(arr[::2])
print(arr[::-1])
print(arr[-3:-1])
# step
print(arr[1:5:2])


[3 4 5 6 7 8]
[ 5  6  7  8  9 10]
[1 2 3 4]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2  1]
[8 9]
[2 4]


In [59]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2[1,0:4])
print(arr2[0:2,2])
print(arr2[0:2,1:4])

[6 7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
# Data type: numpy.dtype
print(arr.dtype)

int64


In [62]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


# data type: float, int, complex, etc.
* i - integer
* f - float
* c - complex
* b - boolean
* u - unsigned integer
* m - timedelta
* M - datetime
* S - string
* U - Unicode string
* V - raw bytes(void)

In [63]:
arr = np.array([1,2,3,4,5],dtype='S')
print(arr.dtype)

|S1


In [68]:
# defining the size of the array
arr = np.array([1,2,3,4,5],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [69]:
ar = np.array(['a','2','3'],dtype = 'i')
print(ar)

ValueError: invalid literal for int() with base 10: 'a'

In [76]:
# astype() method is used to convert the data type of the array.
ar = np.array([1.1,2.1,3.1])
new_ar = ar.astype('i')
# new_ar = ar.astype(int)
print(new_ar)
print(ar.dtype)
print(new_ar.dtype)


[1 2 3]
float64
int32


In [ ]:
# copy : make a copy of an array
# view

In [81]:
arr = np.array([1,2,3,4,5])
print(arr)
x = arr.copy()
print(x)
# want to change the 3 to 42 in x
x[2] = 42
print(x)


[1 2 3 4 5]
[1 2 3 4 5]
[ 1  2 42  4  5]


In [85]:
# view : it will create a copy of the array also any change is there so it will reflect in the original array.
arr = np.array([1,2,3,4,5])
x = arr.view()
print(x)
x[2]=42
print(x)
print(arr)

[1 2 3 4 5]
[ 1  2 42  4  5]
[ 1  2 42  4  5]


In [88]:
print(arr)
arr[0]=30
print(arr)
print(x)

[30  2 42  4  5]
[30  2 42  4  5]
[30  2 42  4  5]
