# NUMPY Introduction
* used for working with arrays
* we can use it for linear algebra, Fourier transform, signal processing, and matrix operations
* numpy : numerical python
* created in 2005 by Travis E. Oliphant
* why numpy?
    * it is fast , in python we have list that will be slower
    * Numpy aims to provide a high-performance array object, 50x faster than a Python list
* why Numpy array faster than list?
* in Numpy Array we are using same data type for all elements
* in list we can use different data types
* Numpy written in C or C++ for speed or fast computation
* pip install numpy
* ! / %

In [2]:
import numpy as np
print(np.__version__)

2.2.6


In [5]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
# Dimensions
# pandas.series : one dimensional labeled array 
# pandas.DataFrame : two dimensional labeled array

In [13]:
# 0-D array
import numpy as np
arr = np.array(42)
print(arr)
print("dimensions of arr: ",arr.ndim)

42
dimensions of arr:  0


In [16]:
# 1-D Array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print("shape of arr1: ",arr1.shape)
print("dimensions of arr1: ",arr1.ndim)

[1 2 3 4 5]
shape of arr1:  (5,)
dimensions of arr1:  1


In [ ]:
# 2-D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape)
print("dimensions is: ",arr2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
dimensions is:  2


In [20]:
# 3-D Array
arr3 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])
print(arr3)
print("shape is:",arr3.shape)
print("Dimensions are:",arr3.ndim)

[[[1 2 3 4]
  [4 5 6 7]]

 [[1 2 3 4]
  [4 5 6 7]]]
shape is: (2, 2, 4)
Dimensions are: 3


In [22]:
# create 5 dimensional array
arr5 = np.array([1,2,3,4],ndmin=5)
print(arr5)
print(arr5.shape)
print("number of dimensions",arr5.ndim)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)
number of dimensions 5


In [27]:
# access the array elements using indexing
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[5])

6


In [28]:
# get third and fifth element from this array and add them together
print(arr[3] + arr[5])

10


In [36]:
# in 2d Array we can access the elements by row and column
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2[0])
print(arr2[1])
print("3 element of second row: ",arr2[1,2])
print("2nd element of first row:",arr2[0,1])

[1 2 3 4 5]
[ 6  7  8  9 10]
3 element of second row:  8
2nd element of first row: 2


In [46]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3.ndim)
print(arr3[0])
print(arr3[0,0])
print(arr3[0,0,0])
print(arr3[1,0,1])
print(arr3[1,1,-1])
print(arr3[-1,-2,-1])


3
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
8
12
9


In [54]:
# slicing [start:end:step]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[2:8])
print(arr[4:])
print(arr[:4])
print(arr[::2])
print(arr[::-1])
print(arr[-3:-1])
# step
print(arr[1:5:2])


[3 4 5 6 7 8]
[ 5  6  7  8  9 10]
[1 2 3 4]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2  1]
[8 9]
[2 4]


In [59]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2[1,0:4])
print(arr2[0:2,2])
print(arr2[0:2,1:4])

[6 7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
# Data type: numpy.dtype
print(arr.dtype)

int64


In [62]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


# data type: float, int, complex, etc.
* i - integer
* f - float
* c - complex
* b - boolean
* u - unsigned integer
* m - timedelta
* M - datetime
* S - string
* U - Unicode string
* V - raw bytes(void)

In [63]:
arr = np.array([1,2,3,4,5],dtype='S')
print(arr.dtype)

|S1


In [68]:
# defining the size of the array
arr = np.array([1,2,3,4,5],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [69]:
ar = np.array(['a','2','3'],dtype = 'i')
print(ar)

ValueError: invalid literal for int() with base 10: 'a'

In [76]:
# astype() method is used to convert the data type of the array.
ar = np.array([1.1,2.1,3.1])
new_ar = ar.astype('i')
# new_ar = ar.astype(int)
print(new_ar)
print(ar.dtype)
print(new_ar.dtype)


[1 2 3]
float64
int32


In [ ]:
# copy : make a copy of an array
# view

In [81]:
arr = np.array([1,2,3,4,5])
print(arr)
x = arr.copy()
print(x)
# want to change the 3 to 42 in x
x[2] = 42
print(x)


[1 2 3 4 5]
[1 2 3 4 5]
[ 1  2 42  4  5]


In [85]:
# view : it will create a copy of the array also any change is there so it will reflect in the original array.
arr = np.array([1,2,3,4,5])
x = arr.view()
print(x)
x[2]=42
print(x)
print(arr)

[1 2 3 4 5]
[ 1  2 42  4  5]
[ 1  2 42  4  5]


In [88]:
print(arr)
arr[0]=30
print(arr)
print(x)

[30  2 42  4  5]
[30  2 42  4  5]
[30  2 42  4  5]


In [1]:
# Numpy array Reshaping(change the shape of an array)


In [10]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
print(arr.shape)
print(arr.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1


In [12]:
# reshape 1-D array to 2-D array
newarr = arr.reshape(4,3) # 4 rows, 3 columns
print(newarr)
print(newarr.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2


In [13]:
# reshape 1-D array to 3-D array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2) # 2 rows, 3 columns, 2 depth
print(newarr)
print(newarr.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
# newarr = arr.reshape(3,3) # it will give error because we have 8 elements in the array and we are trying to reshape it to 3x3 which is 9 elements. so it will give error.
print(newarr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [25]:
# 3D array with 2*2
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,2,-1)# -1 means that we do not know the number of columns, but we want 2 rows. so it will automatically calculate the number of columns.
print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# flatten() : it will convert the multi-dimensional array to 1D array.
# reshape(-1)
# convert 2d to 1d array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
newarr = arr.reshape(-1)# -1 means that we do not know the number of columns, but we want 1 row. so it will automatically calculate the number of columns.
print(newarr)
print(newarr.ndim)

[[1 2 3]
 [4 5 6]]
2
[1 2 3 4 5 6]
1


In [31]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.ndim)
newarr = arr.reshape(-1)
print(newarr)
print(newarr.ndim)

3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [45]:
# Numpy Array Iteration (going through each element of an array one by one)
arr = np.array([11,22,33])
print(arr)
for i in arr:
    print(i,end=" ")

[11 22 33]
11 22 33 

In [49]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]


In [53]:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)
    for y in x:
        print(y)
    

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [54]:
# 3-D numpy array
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [61]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    # print(x)
    for y in x:
        # print(y)
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [63]:
# nditer() : it will iterate through the array in a flat order.
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [82]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]): # : whole array , ::2 every second element
    print(x)

1
3
5
7


In [2]:
l1 = [11,22,33,44,55]
for i,j in enumerate(l1):
    print(f"index: {i} value: {j}")

index: 0 value: 11
index: 1 value: 22
index: 2 value: 33
index: 3 value: 44
index: 4 value: 55


In [4]:
# ndenumerate() : it will iterate through the array in a flat order and also give the index of the element.
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
for x,y in np.ndenumerate(arr):
    print(x,y)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10


In [5]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [6]:
# quize
import numpy as np
arr = np.array(['a', 'b', 'c'])
for x in arr:
    print('Hello '+ x)
# hello a b c
# hello ['a', 'b', 'c']
# hello a
# hello b
# hello c

Hello a
Hello b
Hello c


In [25]:
# concatenate() : concatenates two arrays
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr=np.concatenate([arr1, arr2])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [18]:
# join the 2-d arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1) # 0:rows, 1:columns 
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [27]:
# stack() : stack(joining) the arrays along a new axis.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=0) # 0:rows, 1:columns
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
# stacking along rows
# hstack() : stack(joining) the arrays along a new axis(horizontal).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


In [ ]:
# vstack() : stack(joining) the arrays along a new axis(vertical).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# dstack() : stack(joining) the arrays along a new axis(depth).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [34]:
# Numpy Splitting : splitting the array into multiple sub-arrays.
# array_split() 

In [38]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3) # split the array into 3 sub-arrays
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [41]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4) 
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])

[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3 4]
[5]
[6]


In [44]:
# searching Array
# where() : it will return the indices of the elements that satisfy the condition.
arr = np.array([1,2,3,4,4,5,6,4,4,7,8,9,4])
x = np.where(arr == 4)
print("index of 4 is ", x)

index of 4 is  (array([ 3,  4,  7,  8, 12]),)


In [46]:
l1 = [10,14,93,41,85,23,54,76,32,12]
x = []
for i in l1:
    if i%2==0:
        x.append(i)
print(x)

[10, 14, 54, 76, 32, 12]


In [50]:
arr = np.array([10,14,93,41,85,23,54,76,32,12])
x = np.where(arr%2==0)
print(x)
for i in x:
    print(arr[i])

(array([0, 1, 6, 7, 8, 9]),)
[10 14 54 76 32 12]
